In [1]:
import numpy as np

In [2]:
np.__version__


'2.3.3'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(9,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

9

#### 2D Array

In [22]:
arr2 = np.array([[1,4,5], [6,7,4]])

In [23]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [24]:
arr2.shape #row X col

(2, 3)

In [25]:
arr2.dtype

dtype('int64')

In [26]:
arr2.size

6

In [27]:
arr2.ndim

2

#### 3D array

In [31]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,5,7],[4,6,8]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 7],
        [4, 6, 8]]])

In [32]:
arr3.size

12

In [33]:
arr3.shape

(2, 2, 3)

In [35]:
arr3.ndim

3

### Create random array

In [38]:
randomarr = np.random.rand(3,2,3)
randomarr

array([[[0.48733293, 0.08455107, 0.47654929],
        [0.47815714, 0.3307147 , 0.39415919]],

       [[0.7939097 , 0.50408484, 0.07276128],
        [0.56050529, 0.42155288, 0.63648059]],

       [[0.43529175, 0.1591877 , 0.83508109],
        [0.9795566 , 0.99110899, 0.52507705]]])

In [110]:
zeros = np.zeros((3, 2, 3))


In [47]:
np.full((3,2,3),9)

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [49]:
np.ones((2,3,12))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [69]:
arr3[1][0][1]

np.int64(5)

In [70]:
arr3[1,0,1]

np.int64(5)

In [71]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [72]:
np.add(a1,a2)

array([[[0.39787398, 1.72459898],
        [1.01457668, 1.22513812],
        [1.19925248, 0.62112082]],

       [[0.3815722 , 1.55999252],
        [0.79261329, 1.58904939],
        [0.14224021, 0.96057375]]])

In [73]:
np.subtract(a2,a1)

array([[[-0.32016325,  0.02245895],
        [-0.59234735,  0.03816558],
        [ 0.41272204, -0.11899267]],

       [[-0.33078999, -0.12271877],
        [-0.09249364, -0.08406155],
        [-0.13440224, -0.80127078]]])

In [74]:
np.multiply(a1,a2)

array([[[1.39497999e-02, 7.43434307e-01],
        [1.69622616e-01, 3.74876698e-01],
        [3.16966760e-01, 9.29079526e-02]],

       [[9.04383239e-03, 6.04629194e-01],
        [1.54920190e-01, 6.29502903e-01],
        [5.42078993e-04, 7.01667670e-02]]])

In [75]:
np.divide(a1,a2)

array([[[ 9.2398719 ,  0.9742894 ],
        [ 3.80580863,  0.93957813],
        [ 0.48792983,  1.47395342]],

       [[14.02778919,  1.17076603],
        [ 1.26422239,  1.1117106 ],
        [35.29515542, 11.0597092 ]]])

In [77]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,5)
log = np.log(4)
min = np.min(a1)
max = np.max(a2)

In [80]:
log

np.float64(1.3862943611198906)

In [81]:
 arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 5, 7],
        [4, 6, 8]]])

In [82]:
arr3[0][0][1] = 10

In [83]:
arr3

array([[[ 1, 10,  3],
        [ 4,  5,  6]],

       [[ 3,  5,  7],
        [ 4,  6,  8]]])

In [85]:
arr3.sort()
arr3

array([[[ 1,  3, 10],
        [ 4,  5,  6]],

       [[ 3,  5,  7],
        [ 4,  6,  8]]])

In [86]:
arr3.shape

(2, 2, 3)

In [94]:
arr3_reshape = arr3.reshape((3,2,-1))
arr3_reshape

array([[[ 1,  3],
        [10,  4]],

       [[ 5,  6],
        [ 3,  5]],

       [[ 7,  4],
        [ 6,  8]]])

### Appending and inserting

In [103]:
new = np.ones((3, 2, 3))
new

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [106]:
appd = np.append(arr3, new, axis=0)
appd

array([[[ 1.,  3., 10.],
        [ 4.,  5.,  6.]],

       [[ 3.,  5.,  7.],
        [ 4.,  6.,  8.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [113]:
insert = np.insert(zeros, 1, new, axis = 0)
insert

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Save And delete Arrays

In [115]:
arr4 = np.random.rand(3,4,5)
arr4

array([[[0.99726421, 0.40171838, 0.08670718, 0.48315283, 0.16828997],
        [0.47960274, 0.2731463 , 0.56195408, 0.73966773, 0.95117979],
        [0.60001251, 0.35317659, 0.0610993 , 0.10963954, 0.27445792],
        [0.84140663, 0.98355473, 0.1154458 , 0.55762749, 0.9204795 ]],

       [[0.60001043, 0.9325634 , 0.833716  , 0.61539579, 0.26454813],
        [0.37554882, 0.93161972, 0.59424287, 0.55115273, 0.95879306],
        [0.77523917, 0.52351241, 0.20123681, 0.13350809, 0.4561445 ],
        [0.42137071, 0.03624645, 0.7401312 , 0.27582288, 0.66868064]],

       [[0.26612868, 0.68238652, 0.29571721, 0.00458969, 0.19439857],
        [0.16728039, 0.7264106 , 0.78899781, 0.12275466, 0.79205165],
        [0.96958751, 0.65115529, 0.07761783, 0.99738696, 0.00780991],
        [0.51590748, 0.24127362, 0.61554592, 0.26721253, 0.5791551 ]]])

In [122]:
arr5 = np.delete(arr4, 0, axis=1)

In [123]:
arr5

array([[[0.47960274, 0.2731463 , 0.56195408, 0.73966773, 0.95117979],
        [0.60001251, 0.35317659, 0.0610993 , 0.10963954, 0.27445792],
        [0.84140663, 0.98355473, 0.1154458 , 0.55762749, 0.9204795 ]],

       [[0.37554882, 0.93161972, 0.59424287, 0.55115273, 0.95879306],
        [0.77523917, 0.52351241, 0.20123681, 0.13350809, 0.4561445 ],
        [0.42137071, 0.03624645, 0.7401312 , 0.27582288, 0.66868064]],

       [[0.16728039, 0.7264106 , 0.78899781, 0.12275466, 0.79205165],
        [0.96958751, 0.65115529, 0.07761783, 0.99738696, 0.00780991],
        [0.51590748, 0.24127362, 0.61554592, 0.26721253, 0.5791551 ]]])

In [124]:
np.save("new_array", arr5)

In [125]:
np.load("new_array.npy")

array([[[0.47960274, 0.2731463 , 0.56195408, 0.73966773, 0.95117979],
        [0.60001251, 0.35317659, 0.0610993 , 0.10963954, 0.27445792],
        [0.84140663, 0.98355473, 0.1154458 , 0.55762749, 0.9204795 ]],

       [[0.37554882, 0.93161972, 0.59424287, 0.55115273, 0.95879306],
        [0.77523917, 0.52351241, 0.20123681, 0.13350809, 0.4561445 ],
        [0.42137071, 0.03624645, 0.7401312 , 0.27582288, 0.66868064]],

       [[0.16728039, 0.7264106 , 0.78899781, 0.12275466, 0.79205165],
        [0.96958751, 0.65115529, 0.07761783, 0.99738696, 0.00780991],
        [0.51590748, 0.24127362, 0.61554592, 0.26721253, 0.5791551 ]]])